language: c++
compiler:
  - gcc
  - clang
script: ./configure --disable-linuxmodule --enable-ip6 --enable-json && make && make check
addons:
  apt:
    packages:
    - tcpdump
    - libpcap-dev
    - time
sudo: false
